DataTables version 1.10.11 fix
Update package.son for DataTables version ^1.10.9 (where the caret updates to the most recent major version (the first number). ^1.10.9 will match any 1.x.x release including 1.3.0, but will hold off on 2.0.0.)

Adds basic DataTable API functionality test spec:
* test table sort ordering
* test table search

This code update closes [Assets-FrontEnd Issue #459 - DataTable has fixed version 1.10.9 in package.json](https://github.com/hmrc/assets-frontend/issues/459)

DataTables.net introduced a breaking change in 1.10.11, throwing an error which blocks `application.min.js` execution.

The issue was reported: [Uncaught TypeError: $(...).DataTable is not a function(…) · Issue #791 · DataTables/DataTables](https://github.com/DataTables/DataTables/issues/791) with test pages deployed to [datatables-test.mod.bz](http://datatables-test.mod.bz/)

The response confirmed the unintended breaking change and provided the resolution, which is implemented in this PR.